### ISSUE TITLE
Unable to load library on android. 

### ISSUE THREAD

**Issue by RichardCowart-ValleyIT** [impleotv/misbcore-native-lib-release#2]
ava.lang.UnsatisfiedLinkError: dlopen failed: library "libstdc++.so.6" not found

**Comment by RichardCowart-ValleyIT** [comment]
It there a sample Android project that is available to use.  I have the library working on linux fine.  But not Android

**Comment by impleotv** [comment]
Hi Richard,

We only support Linux (x64/Arm64)  and Windows...

Alex
